import { Navbar } from "@/components/NavBar";
import { CartContextProvider } from "@/context/CartContext";
import { ProductContextProvier } from "@/context/ProductContext";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Profile.Fyi | Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster
        position="top-center"
        reverseOrder={false}
        containerStyle={{ top: "10%" }}
      />
        <ProductContextProvier>
          <CartContextProvider>
            <Navbar/>
            {children}
          </CartContextProvider>
        </ProductContextProvier>
        
      </body>
    </html>
  );
}
